$ErrorActionPreference = "Stop"
$base = "c:\Users\HuiDu_OwO\Downloads\GitHub\MusicBox"
$oldRoot = "$base\src\main\java\ru\spliterash\musicbox"
$newRoot = "$base\src\main\java\com\huidu\musicbox"

# ============== 文件复制映射 ==============
$fileMap = @{
    "MusicBox.java" = "MusicBox.java"
    "MusicBoxConfig.java" = "MusicBoxConfig.java"
    "MusicBoxEventHandler.java" = "MusicBoxEventHandler.java"
    "Lang.java" = "common\lang\Lang.java"
}

# bstats files
$bstatsMap = @{
    "bstats\MetricsBase.java" = "common\stats\MetricsBase.java"
    "bstats\bukkit\Metrics.java" = "common\stats\bukkit\Metrics.java"
    "bstats\charts\AdvancedBarChart.java" = "common\stats\charts\AdvancedBarChart.java"
    "bstats\charts\AdvancedPie.java" = "common\stats\charts\AdvancedPie.java"
    "bstats\charts\CustomChart.java" = "common\stats\charts\CustomChart.java"
    "bstats\charts\DrilldownPie.java" = "common\stats\charts\DrilldownPie.java"
    "bstats\charts\MultiLineChart.java" = "common\stats\charts\MultiLineChart.java"
    "bstats\charts\SimpleBarChart.java" = "common\stats\charts\SimpleBarChart.java"
    "bstats\charts\SimplePie.java" = "common\stats\charts\SimplePie.java"
    "bstats\charts\SingleLineChart.java" = "common\stats\charts\SingleLineChart.java"
    "bstats\config\MetricsConfig.java" = "common\stats\config\MetricsConfig.java"
    "bstats\json\JsonObjectBuilder.java" = "common\stats\json\JsonObjectBuilder.java"
}

# commands files
$cmdMap = @{
    "commands\MusicBoxExecutor.java" = "module\command\MusicBoxExecutor.java"
    "commands\SubCommand.java" = "module\command\SubCommand.java"
    "commands\subcommands\AbstractSelect.java" = "module\command\subcommands\AbstractSelect.java"
    "commands\subcommands\AutoPlayExecutor.java" = "module\command\subcommands\AutoPlayExecutor.java"
    "commands\subcommands\EditExecutor.java" = "module\command\subcommands\EditExecutor.java"
    "commands\subcommands\GiveExecutor.java" = "module\command\subcommands\GiveExecutor.java"
    "commands\subcommands\Mute.java" = "module\command\subcommands\Mute.java"
    "commands\subcommands\PlayExecutor.java" = "module\command\subcommands\PlayExecutor.java"
    "commands\subcommands\PlaylistExecutor.java" = "module\command\subcommands\PlaylistExecutor.java"
    "commands\subcommands\ReloadExecutor.java" = "module\command\subcommands\ReloadExecutor.java"
    "commands\subcommands\ShopExecutor.java" = "module\command\subcommands\ShopExecutor.java"
    "commands\subcommands\ShopMusicExecutor.java" = "module\command\subcommands\ShopMusicExecutor.java"
    "commands\subcommands\SilentExecutor.java" = "module\command\subcommands\SilentExecutor.java"
    "commands\subcommands\SongTagExecutor.java" = "module\command\subcommands\SongTagExecutor.java"
    "commands\subcommands\SpeedExecutor.java" = "module\command\subcommands\SpeedExecutor.java"
    "commands\subcommands\StopExecutor.java" = "module\command\subcommands\StopExecutor.java"
    "commands\subcommands\TextPlayerExecutor.java" = "module\command\subcommands\TextPlayerExecutor.java"
    "commands\subcommands\VolumeExecutor.java" = "module\command\subcommands\VolumeExecutor.java"
}

# config files
$cfgMap = @{
    "config\ConfigManager.java" = "common\config\ConfigManager.java"
    "config\GUIButtonRegistry.java" = "common\config\GUIButtonRegistry.java"
    "config\GUIConfigManager.java" = "common\config\GUIConfigManager.java"
    "config\GUISectionConfigLoader.java" = "common\config\GUISectionConfigLoader.java"
    "config\LanguageConfig.java" = "common\config\LanguageConfig.java"
    "config\SmartConfigManager.java" = "common\config\SmartConfigManager.java"
    "config\SongAliasConfig.java" = "common\config\SongAliasConfig.java"
}

# customPlayers files
$cpMap = @{
    "customPlayers\abstracts\AbstractBlockPlayer.java" = "core\player\AbstractBlockPlayer.java"
    "customPlayers\interfaces\IPlayList.java" = "api\player\IPlayList.java"
    "customPlayers\interfaces\MusicBoxSongPlayer.java" = "api\player\MusicBoxSongPlayer.java"
    "customPlayers\interfaces\PlayerSongPlayer.java" = "api\player\PlayerSongPlayer.java"
    "customPlayers\interfaces\PositionPlayer.java" = "api\player\PositionPlayer.java"
    "customPlayers\loop\LoopMode.java" = "core\player\loop\LoopMode.java"
    "customPlayers\models\MusicBoxSongPlayerModel.java" = "core\player\models\MusicBoxSongPlayerModel.java"
    "customPlayers\models\PlayerPlayerModel.java" = "core\player\models\PlayerPlayerModel.java"
    "customPlayers\models\RangePlayerModel.java" = "core\player\models\RangePlayerModel.java"
    "customPlayers\playlist\ListPlaylist.java" = "core\player\playlist\ListPlaylist.java"
    "customPlayers\playlist\SingletonPlayList.java" = "core\player\playlist\SingletonPlayList.java"
    "customPlayers\FastNotePlayback.java" = "core\player\FastNotePlayback.java"
    "customPlayers\PlayerManager.java" = "core\player\PlayerManager.java"
    "customPlayers\SongTickIndex.java" = "core\player\SongTickIndex.java"
    "customPlayers\VolumeManager.java" = "core\player\VolumeManager.java"
    "customPlayers\objects\jukebox\JukeboxPlayer.java" = "module\jukebox\JukeboxPlayer.java"
    "customPlayers\objects\jukebox\JukeboxPlaylistImpl.java" = "module\jukebox\JukeboxPlaylistImpl.java"
    "customPlayers\objects\jukebox\JukeboxPlaylistInitException.java" = "module\jukebox\JukeboxPlaylistInitException.java"
    "customPlayers\objects\RadioPlayer.java" = "module\radio\RadioPlayer.java"
    "customPlayers\objects\SignPlayer.java" = "module\sign\SignPlayer.java"
    "customPlayers\objects\SignTextDisplayPlayer.java" = "module\sign\SignTextDisplayPlayer.java"
    "customPlayers\objects\SpeakerPlayer.java" = "module\speaker\SpeakerPlayer.java"
    "customPlayers\objects\IdleTextDisplay.java" = "module\textdisplay\IdleTextDisplay.java"
    "customPlayers\objects\TextDisplayContent.java" = "module\textdisplay\TextDisplayContent.java"
    "customPlayers\objects\TextDisplayHandle.java" = "module\textdisplay\TextDisplayHandle.java"
    "customPlayers\objects\TextDisplayPlayer.java" = "module\textdisplay\TextDisplayPlayer.java"
    "customPlayers\objects\TextDisplayPlayerListener.java" = "module\textdisplay\TextDisplayPlayerListener.java"
    "customPlayers\objects\TextDisplayPlayerManager.java" = "module\textdisplay\TextDisplayPlayerManager.java"
    "customPlayers\objects\TextDisplayVisual.java" = "module\textdisplay\TextDisplayVisual.java"
}

# db files
$dbMap = @{
    "db\AbstractBase.java" = "common\db\AbstractBase.java"
    "db\DatabaseLoader.java" = "common\db\DatabaseLoader.java"
    "db\RuntimeDatabaseUtils.java" = "common\db\RuntimeDatabaseUtils.java"
    "db\model\PlayerPlayListModel.java" = "common\db\model\PlayerPlayListModel.java"
    "db\types\ConnectionWrapper.java" = "common\db\types\ConnectionWrapper.java"
    "db\types\MySQL.java" = "common\db\types\MySQL.java"
    "db\types\SQLite.java" = "common\db\types\SQLite.java"
    "db\utils\NamedParamStatement.java" = "common\db\utils\NamedParamStatement.java"
    "db\utils\ResultSetRow.java" = "common\db\utils\ResultSetRow.java"
}

# edit files
$editMap = @{
    "edit\EditAction.java" = "module\edit\EditAction.java"
    "edit\EditHistory.java" = "module\edit\EditHistory.java"
    "edit\MusicEditClipboardCoordinator.java" = "module\edit\MusicEditClipboardCoordinator.java"
    "edit\MusicEditCloseCoordinator.java" = "module\edit\MusicEditCloseCoordinator.java"
    "edit\MusicEditGUI.java" = "module\edit\MusicEditGUI.java"
    "edit\MusicEditInstrumentMenuRenderer.java" = "module\edit\MusicEditInstrumentMenuRenderer.java"
    "edit\MusicEditListener.java" = "module\edit\MusicEditListener.java"
    "edit\MusicEditNoteRenderer.java" = "module\edit\MusicEditNoteRenderer.java"
    "edit\MusicEditPreviewHighlighter.java" = "module\edit\MusicEditPreviewHighlighter.java"
    "edit\MusicEditSelectionManager.java" = "module\edit\MusicEditSelectionManager.java"
    "edit\MusicEditSoundPlayer.java" = "module\edit\MusicEditSoundPlayer.java"
    "edit\MusicEditTextInputManager.java" = "module\edit\MusicEditTextInputManager.java"
    "edit\MusicNote.java" = "module\edit\MusicNote.java"
    "edit\NoteClipboard.java" = "module\edit\NoteClipboard.java"
    "edit\NotePitchMapper.java" = "module\edit\NotePitchMapper.java"
    "edit\PlayerInventoryState.java" = "module\edit\PlayerInventoryState.java"
    "edit\PlayerMusic.java" = "module\edit\PlayerMusic.java"
    "edit\PlayerMusicDiscHelper.java" = "module\edit\PlayerMusicDiscHelper.java"
    "edit\PlayerMusicManager.java" = "module\edit\PlayerMusicManager.java"
    "edit\audio\ResourcePackInstrumentUtils.java" = "module\edit\audio\ResourcePackInstrumentUtils.java"
    "edit\gui\BPMSettingsGUI.java" = "module\edit\gui\BPMSettingsGUI.java"
    "edit\gui\EditGUIListener.java" = "module\edit\gui\EditGUIListener.java"
    "edit\gui\EditMenuGUI.java" = "module\edit\gui\EditMenuGUI.java"
    "edit\gui\ExitConfirmGUI.java" = "module\edit\gui\ExitConfirmGUI.java"
    "edit\gui\ManagePublishedGUI.java" = "module\edit\gui\ManagePublishedGUI.java"
    "edit\gui\MusicSelectGUI.java" = "module\edit\gui\MusicSelectGUI.java"
    "edit\gui\PastePreviewGUI.java" = "module\edit\gui\PastePreviewGUI.java"
    "edit\gui\PlayerMusicShopGUI.java" = "module\edit\gui\PlayerMusicShopGUI.java"
    "edit\gui\PublishConfirmGUI.java" = "module\edit\gui\PublishConfirmGUI.java"
    "edit\gui\PublishGUI.java" = "module\edit\gui\PublishGUI.java"
    "edit\gui\PurchaseConfirmGUI.java" = "module\edit\gui\PurchaseConfirmGUI.java"
    "edit\gui\SettingsMenuGUI.java" = "module\edit\gui\SettingsMenuGUI.java"
    "edit\io\MidiAutoConverter.java" = "module\edit\io\MidiAutoConverter.java"
    "edit\io\MidiImporter.java" = "module\edit\io\MidiImporter.java"
    "edit\io\MusicFileImporter.java" = "module\edit\io\MusicFileImporter.java"
    "edit\io\NBSEncoder.java" = "module\edit\io\NBSEncoder.java"
    "edit\io\NBSExporter.java" = "module\edit\io\NBSExporter.java"
    "edit\io\NBSImporter.java" = "module\edit\io\NBSImporter.java"
    "edit\io\NoteBlockSongConverter.java" = "module\edit\io\NoteBlockSongConverter.java"
    "edit\publish\PublishedMusic.java" = "module\edit\publish\PublishedMusic.java"
    "edit\publish\PublishedMusicManager.java" = "module\edit\publish\PublishedMusicManager.java"
}

# events, gui, hooks, lifecycle, minecraft, players, shadow, song, utils, web maps
$moreMaps = @{
    "events\JukeboxChestEvent.java" = "api\event\JukeboxChestEvent.java"
    "events\JukeboxHopperEvent.java" = "api\event\JukeboxHopperEvent.java"
    "events\MusicBoxPauseEvent.java" = "api\event\MusicBoxPauseEvent.java"
    "events\MusicBoxResumeEvent.java" = "api\event\MusicBoxResumeEvent.java"
    "events\MusicBoxSongChangeEvent.java" = "api\event\MusicBoxSongChangeEvent.java"
    "events\MusicBoxStopEvent.java" = "api\event\MusicBoxStopEvent.java"
    "events\SourcedBlockRedstoneEvent.java" = "api\event\SourcedBlockRedstoneEvent.java"
    "gui\ButtonFactory.java" = "module\gui\ButtonFactory.java"
    "gui\DeleteConfirmGUI.java" = "module\gui\DeleteConfirmGUI.java"
    "gui\GUIActions.java" = "module\gui\GUIActions.java"
    "gui\GUIInputManager.java" = "module\gui\GUIInputManager.java"
    "gui\GUIPlaylistActions.java" = "module\gui\GUIPlaylistActions.java"
    "gui\GUIShopActions.java" = "module\gui\GUIShopActions.java"
    "gui\GUISignActions.java" = "module\gui\GUISignActions.java"
    "gui\RecentSongsGUI.java" = "module\gui\RecentSongsGUI.java"
    "gui\layout\LayoutParser.java" = "module\gui\layout\LayoutParser.java"
    "gui\playlist\PlayListEditorGUI.java" = "module\gui\playlist\PlayListEditorGUI.java"
    "gui\playlist\PlayListListGUI.java" = "module\gui\playlist\PlayListListGUI.java"
    "gui\song\ControlPanelButtonFactory.java" = "module\gui\song\ControlPanelButtonFactory.java"
    "gui\song\ControlPanelProgressRenderer.java" = "module\gui\song\ControlPanelProgressRenderer.java"
    "gui\song\ControlPanelSongListRenderer.java" = "module\gui\song\ControlPanelSongListRenderer.java"
    "gui\song\SearchResultGUI.java" = "module\gui\song\SearchResultGUI.java"
    "gui\song\SongContainerGUI.java" = "module\gui\song\SongContainerGUI.java"
    "gui\song\SongPlayerControlGUI.java" = "module\gui\song\SongPlayerControlGUI.java"
    "gui\textplayer\TextDisplayPlayerEditGUI.java" = "module\gui\textplayer\TextDisplayPlayerEditGUI.java"
    "hooks\MusicBoxExpansion.java" = "module\hook\MusicBoxExpansion.java"
    "lifecycle\BundledResourceExtractor.java" = "core\lifecycle\BundledResourceExtractor.java"
    "lifecycle\ModuleRuntimeSync.java" = "core\lifecycle\ModuleRuntimeSync.java"
    "lifecycle\ReloadPlaybackState.java" = "core\lifecycle\ReloadPlaybackState.java"
    "minecraft\gui\GUI.java" = "module\gui\minecraft\GUI.java"
    "minecraft\gui\InventoryAction.java" = "module\gui\minecraft\InventoryAction.java"
    "minecraft\gui\actions\ClickAction.java" = "module\gui\minecraft\actions\ClickAction.java"
    "minecraft\gui\actions\PlayerClickAction.java" = "module\gui\minecraft\actions\PlayerClickAction.java"
    "minecraft\jukebox\IJukebox.java" = "module\jukebox\minecraft\IJukebox.java"
    "minecraft\jukebox\JukeboxFactory.java" = "module\jukebox\minecraft\JukeboxFactory.java"
    "minecraft\jukebox\PaperJukebox.java" = "module\jukebox\minecraft\PaperJukebox.java"
    "players\AutoPlayService.java" = "core\playback\AutoPlayService.java"
    "players\PlaybackContext.java" = "core\playback\PlaybackContext.java"
    "players\PlayerWrapper.java" = "core\playback\PlayerWrapper.java"
    "shadow\nbteditor\NBTEditor.java" = "shadow\nbteditor\NBTEditor.java"
    "song\MusicBoxSong.java" = "core\song\MusicBoxSong.java"
    "song\MusicBoxSongContainer.java" = "core\song\MusicBoxSongContainer.java"
    "song\MusicBoxSongManager.java" = "core\song\MusicBoxSongManager.java"
    "song\SongNullException.java" = "core\song\SongNullException.java"
    "song\SongContainerFactory.java" = "core\song\SongContainerFactory.java"
    "song\songContainers\containers\SingletonContainer.java" = "core\song\songContainers\containers\SingletonContainer.java"
    "song\songContainers\factory\FolderContainerFactory.java" = "core\song\songContainers\factory\FolderContainerFactory.java"
    "song\songContainers\factory\ListContainerFactory.java" = "core\song\songContainers\factory\ListContainerFactory.java"
    "song\songContainers\factory\SingletonContainerFactory.java" = "core\song\songContainers\factory\SingletonContainerFactory.java"
    "song\songContainers\types\FullSongContainer.java" = "core\song\songContainers\types\FullSongContainer.java"
    "song\songContainers\types\SongContainer.java" = "core\song\songContainers\types\SongContainer.java"
    "song\songContainers\types\SubSongContainer.java" = "core\song\songContainers\types\SubSongContainer.java"
    "utils\ArrayUtils.java" = "common\utils\ArrayUtils.java"
    "utils\AsyncTaskManager.java" = "common\utils\AsyncTaskManager.java"
    "utils\BukkitUtils.java" = "common\utils\BukkitUtils.java"
    "utils\ComponentUtils.java" = "common\utils\ComponentUtils.java"
    "utils\CraftEngineBlockHelper.java" = "common\utils\CraftEngineBlockHelper.java"
    "utils\CraftEngineItemHelper.java" = "common\utils\CraftEngineItemHelper.java"
    "utils\DebugLogger.java" = "common\utils\DebugLogger.java"
    "utils\EconomyUtils.java" = "common\utils\EconomyUtils.java"
    "utils\FaceUtils.java" = "common\utils\FaceUtils.java"
    "utils\FileUtils.java" = "common\utils\FileUtils.java"
    "utils\GUIUtils.java" = "common\utils\GUIUtils.java"
    "utils\HikariLogConfigurator.java" = "common\utils\HikariLogConfigurator.java"
    "utils\ItemModelHelper.java" = "common\utils\ItemModelHelper.java"
    "utils\ItemUtils.java" = "common\utils\ItemUtils.java"
    "utils\JavaUtils.java" = "common\utils\JavaUtils.java"
    "utils\JukeboxPlayableHelper.java" = "common\utils\JukeboxPlayableHelper.java"
    "utils\LocationKey.java" = "common\utils\LocationKey.java"
    "utils\LogLocale.java" = "common\utils\LogLocale.java"
    "utils\MessageUtils.java" = "common\utils\MessageUtils.java"
    "utils\MiniMessageUtils.java" = "common\utils\MiniMessageUtils.java"
    "utils\NoteBlockApiCompatibility.java" = "common\utils\NoteBlockApiCompatibility.java"
    "utils\RedstoneUtils.java" = "common\utils\RedstoneUtils.java"
    "utils\ServerVersionUtils.java" = "common\utils\ServerVersionUtils.java"
    "utils\SignUtils.java" = "common\utils\SignUtils.java"
    "utils\SingletonHolder.java" = "common\utils\SingletonHolder.java"
    "utils\SongUtils.java" = "common\utils\SongUtils.java"
    "utils\SoundUtils.java" = "common\utils\SoundUtils.java"
    "utils\StorageAccess.java" = "common\utils\StorageAccess.java"
    "utils\StringUtils.java" = "common\utils\StringUtils.java"
    "utils\VersionUtils.java" = "common\utils\VersionUtils.java"
    "utils\YamlSupportUtils.java" = "common\utils\YamlSupportUtils.java"
    "utils\cache\CacheCleaner.java" = "common\utils\cache\CacheCleaner.java"
    "utils\cache\CacheUtils.java" = "common\utils\cache\CacheUtils.java"
    "utils\cache\ExpiringCache.java" = "common\utils\cache\ExpiringCache.java"
    "utils\cache\ExpiringCacheCleaner.java" = "common\utils\cache\ExpiringCacheCleaner.java"
    "utils\classes\Pair.java" = "common\utils\classes\Pair.java"
    "utils\classes\PeekList.java" = "common\utils\classes\PeekList.java"
    "utils\nbt\BukkitNbtHandler.java" = "common\utils\nbt\BukkitNbtHandler.java"
    "utils\nbt\NBTFactory.java" = "common\utils\nbt\NBTFactory.java"
    "utils\nbt\NBTHandler.java" = "common\utils\nbt\NBTHandler.java"
    "utils\nbt\NbtConstants.java" = "common\utils\nbt\NbtConstants.java"
    "utils\nbt\NbtEditorHandler.java" = "common\utils\nbt\NbtEditorHandler.java"
    "utils\scheduler\MbTask.java" = "common\utils\scheduler\MbTask.java"
    "utils\scheduler\Scheduler.java" = "common\utils\scheduler\Scheduler.java"
    "web\InstrumentJsonAdapter.java" = "module\web\InstrumentJsonAdapter.java"
    "web\NoteJsonAdapter.java" = "module\web\NoteJsonAdapter.java"
    "web\WebAssetHandler.java" = "module\web\WebAssetHandler.java"
    "web\WebEditorServer.java" = "module\web\WebEditorServer.java"
    "web\WebEditorSession.java" = "module\web\WebEditorSession.java"
    "web\WebInstrumentJsonSupport.java" = "module\web\WebInstrumentJsonSupport.java"
    "web\WebRateLimiter.java" = "module\web\WebRateLimiter.java"
    "web\WebSessionManager.java" = "module\web\WebSessionManager.java"
}

# 合并所有映射
$allMaps = @($fileMap, $bstatsMap, $cmdMap, $cfgMap, $cpMap, $dbMap, $editMap, $moreMaps)

$count = 0
foreach ($map in $allMaps) {
    foreach ($kv in $map.GetEnumerator()) {
        $src = "$oldRoot\$($kv.Key)"
        $dst = "$newRoot\$($kv.Value)"
        if (Test-Path $src) {
            Copy-Item -Path $src -Destination $dst -Force
            $count++
        } else {
            Write-Warning "源文件不存在: $src"
        }
    }
}
Write-Host "文件复制完成: $count 个文件"

